### ISSUE TITLE
jquery dependency

### ISSUE THREAD

**Issue by vylink** [webrouse/n-sandbox#4]
I'v tried to find documentation about how to add jQuery dependency, but no success. Any idea? Just push me a little bit and I will write some documentation of how to add jQuery dependant plugins with this fantastic sandbox. Cheers.

**Comment by michaljurecko** [comment]
Hi, I'm sorry I did not answer. 

Try add path to:
https://github.com/webrouse/n-sandbox/blob/8b904a8bec2959ea6eaccb4ac477c63c727bbd01/build/gulp/config.js#L83
