### ISSUE TITLE
How to compile and use nittro extensions?

### ISSUE THREAD

**Issue by vylink** [webrouse/n-sandbox#5]
Hi,

Any idea How can I use Nittro extensions?

I would like to implement Nittro's Dropzone, but Already spent a day and I still didn't find a way, how to make this extension work.

This is what I've tried:

1. Added nittro-extension into my project:
```
npm install --save nittro-extras
```

2. Set "true" for extras.dropzone to nittroBulder in the config file [here]https://github.com/webrouse/n-sandbox/blob/8b904a8bec2959ea6eaccb4ac477c63c727bbd01/build/gulp/config.js#L33

3. Added following line into the bootstap.js after [this line]https://github.com/webrouse/n-sandbox/blob/8b904a8bec2959ea6eaccb4ac477c63c727bbd01/resources/scripts/bootstrap.js#L33
```
      DropZone: () => _context.lookup('Nittro.Extras.DropZone'),
```

4. I would like to initiate this extension in the [Application.js]https://github.com/webrouse/n-sandbox/blob/master/resources/scripts/app/Application.js for example, but I have no Idea, gow can I do it.

I've tried a multiple ways here, but still no lucky :(

Any help will be really appreciated. If is there somebody who can provide a quick PAID training, how to achieve requested stuff over the skype or phone, let me know, please.

Cheers

**Comment by michaljurecko** [comment]
Hi,

I will reply during weekend, please wait.

Thank you

**Comment by vylink** [comment]
> Hi,
> 
> I will reply during weekend, please wait.
> 
> Thank you

Thank you very much.

**Comment by vylink** [comment]
Any progress about this? Is I mentioned before. I'm prepared to send you some kind of donation. You can contact me directly on hello@vylink.com.

**Comment by michaljurecko** [comment]
Hi @vylink,

I'm sorry I did not provide example last weekend, unfortunately, I did not find the time.

Please, see example in branch `example/dropZone`
- branch: https://github.com/webrouse/n-sandbox/tree/example/dropZone
- diff: https://github.com/webrouse/n-sandbox/compare/master...example/dropZone
- it works for me, please close issue if ok

Donation: Feel free to support project with donation button.
